{% set version = "0.17.10" %}

package:
  name: ruamel.yaml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-{{ version }}.tar.gz
  sha256: 106bc8d6dc6a0ff7c9196a47570432036f41d556b779c6b4e618085f57e39e67

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.5
    - pip
    - ruamel
    - setuptools >=20.6.8
    - wheel
  run:
    - python >=3.5
    - setuptools
    - ruamel.yaml.clib >=0.1.2

test:
  imports:
    - ruamel.yaml

about:
  home: https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML 3.11 which supports YAML1.1
  doc_url: http://yaml.readthedocs.io/
  dev_url: https://sourceforge.net/projects/ruamel-yaml/

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - mwcraig
    - ocefpaf
    - mbargull
