{% set version = "0.15.98" %}

package:
  name: ruamel.yaml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-{{ version }}.tar.gz
  sha256: 937908eb1fab3cc997e88960ccce21a44feb31711c2eb00bb2dbdcad645f5e77

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - ruamel
  run:
    - python
    - setuptools
    - typing  # [py<35]
    - ruamel
    - ruamel.ordereddict  # [py27]

test:
  imports:
    - ruamel.yaml

about:
  home: https://bitbucket.org/ruamel/yaml
  license: MIT
  license_file: LICENSE
  summary: "A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML 3.11 which supports YAML1.1"

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - mwcraig
    - ocefpaf
    - mbargull
