{% set version = "0.15.57" %}

package:
  name: ruamel.yaml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-{{ version }}.tar.gz
  sha256: 7921e9dc0410dc32dd7cb3857b8648f1ab1f29346c24e1edd07f9f4986d6fa23

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - typing  # [py<35]
    - ruamel.ordereddict  # [py27]

test:
  imports:
    - ruamel.yaml

about:
  home: https://bitbucket.org/ruamel/yaml
  license: MIT
  license_file: LICENSE
  summary: "A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML 3.11 which supports YAML1.1"

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - mwcraig
    - ocefpaf
    - mbargull
