travis:
  secure:
    BINSTAR_TOKEN: zDMYuDNah4X3OI3nUT7hfoYBcYPORYdEfzPL8hoyPtt9waXtL1d4IgojbSUdb+dspmD5p6m0D11cZP4zGhGTFr5nAKnIkBonReff2eadLcv3CAgdkhJ5sJMUNJzMF4TcmIWeLwrULhEygn0jIfXao5emLsIYTI96401OaMs49r7cvD4eArq347Ejz9WiyywRyvD9xnFwDHDJLRcL4sTjUQtgcbsNlfzPUYTnzB2yz+nUc5GKS6ugWBRVOP5LidkZn+svID9DiUlrrOEJDEqEmVpuqaYp/N4uaP1L4zgrpAGgJwfM0CC3fmli9QkjtTIPvCRECh9aTc2P7c6wHaz2zqBqVAZYGK8ujq/1/vQho2b1BkulV9lMNX+kSkUEQaD/o98wcvCpU00LA9OFtmSkOFRzAzFbqyDSoLzbA1hFu0k/RvAeZA6Sh3n9+U/FtRm3KfGxtq0V4C64rv9ViQ9pDMUq1drEAx+78s8a+38E2bEYp5QOcXacPZMh0bh9xDyEHe/eVf04ICfEhxRotPBgN05TBEksRBYpRW9Uor8rprT2c/sWV56krUWt0GcAIU8EQ6FNPN0gEh3RTjhs0zBpMxetcbnY4QLpUYnhydfoDWfCmh8VAVGihUJz17tFaalQ83a1+QhIqoIbUhcV1toQ2QCs5kgSI+SrynayAZiQ9o0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
